---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 24h
  url: https://grafana.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k8s-monitoring
  namespace: monitoring
spec:
  interval: 12h
  install:
    strategy:
      name: RetryOnFailure
      retryInterval: 2m
  upgrade:
    strategy:
      name: RetryOnFailure
      retryInterval: 3m
  chart:
    spec:
      chart: k8s-monitoring
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: monitoring
      interval: 12h
  values:
    cluster:
      name: coven
    destinations:
      grafana-cloud-metrics:
        type: prometheus
        urlFrom: convert.nonsensitive(remote.kubernetes.secret.grafana_cloud_metrics.data["prom-host"])
        auth:
          type: basic
          usernameKey: prom-username
          passwordKey: token
        secret:
          create: false
          name: grafana-credentials
          namespace: monitoring
      grafana-cloud-logs:
        type: loki
        urlFrom: convert.nonsensitive(remote.kubernetes.secret.grafana_cloud_logs.data["loki-host"])
        auth:
          type: basic
          usernameKey: loki-username
          passwordKey: token
        secret:
          create: false
          name: grafana-credentials
          namespace: monitoring
      gc-otlp-endpoint:
        type: otlp
        urlFrom: convert.nonsensitive(remote.kubernetes.secret.gc_otlp_endpoint.data["otlp-host"])
        protocol: http
        auth:
          type: basic
          usernameKey: otlp-username
          passwordKey: token
        secret:
          create: false
          name: grafana-credentials
          namespace: monitoring
        metrics:
          enabled: true
        logs:
          enabled: true
        traces:
          enabled: true

    collectors:
      alloy-singleton: {}
      alloy-metrics:
        presets: [clustered, statefulset]
        alloy:
          storagePath: /var/lib/alloy
          mounts:
            extra:
              - name: alloy-wal
                mountPath: /var/lib/alloy
        controller:
          enableStatefulSetAutoDeletePVC: true
          volumeClaimTemplates:
            - metadata:
                name: alloy-wal
              spec:
                accessModes: ["ReadWriteOnce"]
                storageClassName: "rook-ceph"
                resources:
                  requests:
                    storage: 5Gi
      alloy-logs:
        presets: [filesystem-log-reader, daemonset]
        alloy:
          storagePath: /var/lib/alloy
          mounts:
            extra:
              - name: alloy-log-positions
                mountPath: /var/lib/alloy
        controller:
          volumes:
            extra:
              - name: alloy-log-positions
                hostPath:
                  path: /var/alloy-log-storage
                  type: DirectoryOrCreate
      alloy-receiver:
        enabled: true
        alloy:
          extraPorts:
            - name: otlp-grpc
              port: 4317
              targetPort: 4317
              protocol: TCP
            - name: otlp-http
              port: 4318
              targetPort: 4318
              protocol: TCP

    podLogsViaLoki:
      enabled: true
      collector: alloy-logs

    nodeLogs:
      enabled: true
      collector: alloy-logs

    clusterMetrics:
      enabled: true
      collector: alloy-metrics
      kube-state-metrics:

    hostMetrics:
      enabled: true
      collector: alloy-metrics
      linuxHosts:
        enabled: true

    annotationAutodiscovery:
      enabled: true
      collector: alloy-metrics

    clusterEvents:
      enabled: true
      collector: alloy-singleton

    applicationObservability:
      enabled: true
      collector: alloy-receiver
      receivers:
        otlp:
          grpc:
            enabled: true
            port: 4317
          http:
            enabled: true
            port: 4318

    telemetryServices:
      kube-state-metrics:
        deploy: true
      node-exporter:
        deploy: true

    integrations:
      alloy:
        instances:
          - name: alloy
            labelSelectors:
              app.kubernetes.io/name:
                - alloy-metrics
                - alloy-singleton
                - alloy-logs
                - alloy-receiver
