---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 24h
  url: https://kubernetes.github.io/ingress-nginx
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k8s-monitoring
  namespace: monitoring
spec:
  interval: 12h
  install:
    strategy:
      name: RetryOnFailure
      retryInterval: 2m
  upgrade:
    strategy:
      name: RetryOnFailure
      retryInterval: 3m
  chart:
    spec:
      chart: k8s-monitoring
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: monitoring
      interval: 12h
  values:
    cluster:
      name: coven
    destinations:
      - name: grafana-cloud-metrics
        type: prometheus
        urlFrom: convert.nonsensitive(remote.kubernetes.secret.grafana_cloud_metrics.data["prom-host"])
        auth:
          type: basic
          usernameKey: prom-username
          passwordKey: token
        secret:
          create: false
          name: grafana-credentials
          namespace: monitoring
      - name: grafana-cloud-logs
        type: loki
        urlFrom: convert.nonsensitive(remote.kubernetes.secret.grafana_cloud_logs.data["loki-host"])
        auth:
          type: basic
          usernameKey: loki-username
          passwordKey: token
        secret:
          create: false
          name: grafana-credentials
          namespace: monitoring
      - name: gc-otlp-endpoint
        type: otlp
        urlFrom: convert.nonsensitive(remote.kubernetes.secret.gc_otlp_endpoint.data["otlp-host"])
        protocol: http
        auth:
          type: basic
          usernameKey: otlp-username
          passwordKey: token
        secret:
          create: false
          name: grafana-credentials
          namespace: monitoring
        metrics:
          enabled: true
        logs:
          enabled: true
        traces:
          enabled: true
    clusterMetrics:
      enabled: true
      kepler:
        enabled: true
    annotationAutodiscovery:
      enabled: true
    clusterEvents:
      enabled: true
    nodeLogs:
      enabled: true
    podLogs:
      enabled: true
    applicationObservability:
      enabled: true
      receivers:
        otlp:
          grpc:
            enabled: true
            port: 4317
          http:
            enabled: true
            port: 4318
    integrations:
      alloy:
        instances:
          - name: alloy
            labelSelectors:
              app.kubernetes.io/name:
                - alloy-metrics
                - alloy-singleton
                - alloy-logs
                - alloy-receiver
    alloy-metrics:
      enabled: true
    alloy-singleton:
      enabled: true
    alloy-logs:
      enabled: true
    alloy-receiver:
      enabled: true
      alloy:
        extraPorts:
          - name: otlp-grpc
            port: 4317
            targetPort: 4317
            protocol: TCP
          - name: otlp-http
            port: 4318
            targetPort: 4318
            protocol: TCP
